EXTRA_CFLAGS = -Wall
TOOLCHAIN := /home/voduy/Workspace/beagleboneblack_version2/gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-
build:
	$(TOOLCHAIN)gcc -o app_gpio_sysfs gpio_sysfs.c -I$(TOOLCHAIN)/../../include